name: chat

services:
  postgresql:
    image: postgres:18.0
    hostname: postgresql
    volumes:
      - data-postgresql:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    restart: no
    ports:
      - "5432:5432"

  chat:
    build:
      context: ./chat
      tags:
        - chat:0.0.1
        - robertp22/chat:0.0.1
    hostname: chat
    restart: no
    ports:
      - "8090:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_NINJAS_API_KEY=${API_NINJAS_API_KEY}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://authserver:9000
    depends_on:
      - redis
      - authserver

  redis:
    image: redis:8.8.0
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    environment:
      - REDIS_ARGS=--requirepass redispwd --appendonly yes
    restart: no

  authserver:
    image: robertp22/authserver:0.0.1
    hostname: authserver
    ports:
      - "9000:9000"
    restart: no

  elasticsearch:
    image: elasticsearch:9.4.3
    hostname: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data


  kibana:
    image: kibana:9.4.3
    hostname: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=kibana_system
#      - ELASTICSEARCH_PASSWORD=REUruWHquzb=V2_DtWq_
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    depends_on:
      - elasticsearch


volumes:
  data-postgresql:
  data-redis:
  data-elasticsearch:
